name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.github/project.yml'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'

env:
  LANG: en_US.UTF-8
  MAVEN_ARGS: "-Dformat.skip"
jobs:
  build:
    name: JVM Tests - JDK ${{matrix.java.name}}
    runs-on: ${{ matrix.java.os-name }}
    strategy:
      fail-fast: false
      matrix:
        java:
          - {
            name: "17 Eclipse Temurin",
            java-version: 17,
            os-name: "ubuntu-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "21 Eclipse Temurin",
            java-version: 21,
            os-name: "ubuntu-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "17 Zulu OpenJDK",
            java-version: 17,
            os-name: "ubuntu-latest",
            java-vendor: "zulu",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "21 Zulu OpenJDK",
            java-version: 21,
            os-name: "ubuntu-latest",
            java-vendor: "zulu",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "17 Liberica JDK",
            java-version: 17,
            os-name: "ubuntu-latest",
            java-vendor: "liberica",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "21 Liberica JDK",
            java-version: 21,
            os-name: "ubuntu-latest",
            java-vendor: "liberica",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "17 Eclipse Temurin Windows",
            java-version: 17,
            os-name: "windows-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "21 Eclipse Temurin Windows",
            java-version: 21,
            os-name: "windows-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "17 Eclipse Temurin macOS",
            java-version: 17,
            os-name: "macos-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
          - {
            name: "21 Eclipse Temurin macOs",
            java-version: 21,
            os-name: "macos-latest",
            java-vendor: "temurin",
            maven_args: "$MAVEN_ARGS"
          }
    steps:
      - uses: actions/checkout@v5
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-jdk-${{ matrix.java }}-${{ steps.get-date.outputs.date }}
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java.java-vendor }}
          java-version: ${{ matrix.java.java-version }}
      - name: Build with Maven
        run: mvn -B clean install ${{ matrix.java.maven_args }}
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -rf ~/.m2/repository/io/quarkus/quarkus-fs-util*
